"""
Django settings for control_asistencia project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Fallback solo para build (Railway/etc.): en runtime debe existir SECRET_KEY en el entorno.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-build-placeholder-not-for-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.getenv('DEBUG', 'True')).lower() in ['1', 'true', 'yes', 'on']


ALLOWED_HOSTS = ['.onrender.com', '.up.railway.app', '.railway.app', 'localhost', '127.0.0.1']

# Detección correcta de HTTPS detrás de proxy (Railway, Render, etc.)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'https://*.up.railway.app',
    'https://*.railway.app',
    'http://127.0.0.1:8000',
    'https://127.0.0.1:8000',
    'http://localhost:8000',
    'https://localhost:8000',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'control_asistencia.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'control_asistencia.wsgi.application'

# PostgreSQL/Supabase is mandatory. Never fall back to a local database.
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
if not DATABASE_URL:
    raise ImproperlyConfigured(
        'Falta DATABASE_URL. Configura la URL PostgreSQL de Supabase en las '
        'variables del servicio de Railway. SQLite esta deshabilitado.'
    )
try:
    database = dj_database_url.parse(
        DATABASE_URL, conn_max_age=0, conn_health_checks=True, ssl_require=True,
    )
except Exception:
    raise ImproperlyConfigured(
        'DATABASE_URL no es valida. Copia la URL de Supabase (Session pooler); '
        'codifica los caracteres especiales de la contrasena, por ejemplo @ como %40.'
    ) from None
if database.get('ENGINE') != 'django.db.backends.postgresql':
    raise ImproperlyConfigured('DATABASE_URL debe usar PostgreSQL; SQLite no esta permitido.')
if not all(database.get(key) for key in ('HOST', 'NAME', 'USER', 'PASSWORD')):
    raise ImproperlyConfigured('DATABASE_URL debe incluir servidor, base, usuario y contrasena.')
database.setdefault('OPTIONS', {}).update({'sslmode': 'require', 'connect_timeout': 10})
# Compatible with both session and transaction poolers.
database['DISABLE_SERVER_SIDE_CURSORS'] = True
DATABASES = {'default': database}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'es-pe'

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Lima')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / "staticfiles"

# CompressedStaticFilesStorage: más tolerante en deploy; evita fallos por manifest.
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/login/descarga/' 
